# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build, Test & Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout machine repository 
      uses: actions/checkout@v3
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Dependency installation
      run: npm install
    - name: Runing unit tests
      run: npm run test:unit
    
