
name: Build, Test & Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout machine repository 
      uses: actions/checkout@v3
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Dependency installation
      run: npm install
    - name: Runing unit tests
      run: npm run test:unit
    - name: Echo softuni username
      run: echo "DimitarMhnd"

  test-ui:

    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - name: Checkout machine repository 
      uses: actions/checkout@v3
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Dependency installation
      run: npm install
    - name: Installing Playwright browsers
      run: npx playwright install
    - name: Running the application
      run: npm start &
    - name: Runing UI tests
      run: npm run test:ui 
  deploy:
    runs-on: ubuntu-latest
    needs: test-ui
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
               
