
name: Build, Test & Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout machine repository 
      uses: actions/checkout@v3
    - name: Use Node.js version 8.x
      uses: actions/setup-node@v3
      with:
        node-version: 8.x
        cache: 'npm'
    - name: Dependency installation
      run: npm install
    - name: Runing unit tests
      run: npm run test:unit
    - name: Echo softuni username
      run: echo "DimitarMhnd"
    
